// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDilBfGjA_eiYcJuGXDIpbcYGDMq2qTnVY',
    appId: '1:1077707455511:web:084d6453c0cd9cfc983052',
    messagingSenderId: '1077707455511',
    projectId: 'fire-auth-1cb50',
    authDomain: 'fire-auth-1cb50.firebaseapp.com',
    databaseURL: 'https://fire-auth-1cb50-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fire-auth-1cb50.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzXM0n2LYWltglaGwCuPc4qQmXQXefk-E',
    appId: '1:1077707455511:android:98622a571c1a2aed983052',
    messagingSenderId: '1077707455511',
    projectId: 'fire-auth-1cb50',
    databaseURL: 'https://fire-auth-1cb50-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fire-auth-1cb50.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcvW2aozuboXnVP413VkNJpUDDrWPELts',
    appId: '1:1077707455511:ios:b481a7167392c549983052',
    messagingSenderId: '1077707455511',
    projectId: 'fire-auth-1cb50',
    databaseURL: 'https://fire-auth-1cb50-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fire-auth-1cb50.appspot.com',
    iosBundleId: 'com.example.recipeApp',
  );
}
